# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BackMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BackMovies
  pod 'lottie-ios', '~> 4.2'
  pod 'Alamofire', '~> 5.6'
  pod 'youtube-ios-player-helper', '~> 1.0'

end
